dist: bionic
language: dart

jobs:
  include:
    - os: linux
      dist: bionic
      env: LIBRDKAFKA_VERSION=v1.2.2

before_install:
  - sudo apt-get install -y gcc g++ make
  - sudo mkdir -p /usr/local/include/librdkafka
  - git clone https://github.com/edenhill/librdkafka.git
  - pushd librdkafka && git checkout $LIBRDKAFKA_VERSION && ./configure --install-deps && sudo make && sudo make install && popd

install:
  - pub get

script:
  - pub run test
