dist: bionic
language: dart

jobs:
  include:
    - os: linux
      dist: bionic
      env: LIBRDKAFKA_VERSION=v1.2.2_RC1

before_install:
  - sudo apt-get install -y gcc g++ make
  - git clone https://github.com/edenhill/librdkafka.git
  - pushd librdkafka && git checkout $LIBRDKAFKA_VERSION && ./configure --install-deps --includedir=$(pwd) && make && make install && popd

install:
  - pub get

script:
  - pub run test
