name: dart_rdkafka
description: A low level wrapper around the C rdkafka library using Dart's FFI package.
version: 0.0.1
author: Justin D. Fetherolf <fetherolfjd@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  ffi: ^0.1.3-dev.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
