FROM google/dart:2.7

WORKDIR /usr/src
RUN apt-get update && \
apt-get install -y \
vim \
gcc \
g++ \
make \
&& \
apt-get clean && \
apt-get autoremove && \
git clone https://github.com/edenhill/librdkafka.git && \
cd librdkafka && \
git checkout v1.2.2 && \
./configure --install-deps && \
make && \
make install
