FROM google/dart:2.6

WORKDIR /usr/src
RUN apt update && \
apt install -y \
gcc \
g++ \
make \
&& \
git clone https://github.com/edenhill/librdkafka.git && \
cd librdkafka && \
git checkout v1.2.2 && \
./configure --install-deps && \
make && \
make install
